run: main
	./main

main: main.cpp Branch.cpp Tree.cpp Branch.h Tree.h
	g++ main.cpp Branch.cpp Tree.cpp -o main -I/usr/include/opencv4 -lopencv_core -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc